status = [
    "static_analysis",
    "build (x86_64-unknown-linux-gnu, ubuntu-latest)",
    "build (armv7-unknown-linux-gnueabihf, ubuntu-latest)",
    "build (x86_64-apple-darwin, macos-latest)",
    "build (x86_64-pc-windows-msvc, windows-latest)",
    "test (x86_64-unknown-linux-gnu, ubuntu-latest)",
    "test (x86_64-apple-darwin, macos-latest)",
    "docker_tests (happy_path)",
    "docker_tests (happy_path_restart_bob_before_comm)",
    "docker_tests (bob_refunds_using_cancel_and_refund_command)",
    "docker_tests (bob_refunds_using_cancel_and_refund_command_timelock_not_expired_force)",
    "docker_tests (bob_refunds_using_cancel_and_refund_command_timelock_not_expired)",
    "docker_tests (punish)"
]
